name: EpicBossRecoded
version: 1.2.4
description: This plugin lets you fight EpicBosses!
author: ThaH3lper
website: http://dev.bukkit.org/server-mods/epicboss/

main: me.ThaH3lper.com.EpicBoss

commands:
  EpicBoss:
    description: Use it to spawn a boss!
    aliases: [eb]

permissions:
  epicboss.boss:
    description: Gives access to use /eb boss!
    default: op
  epicboss.timers:
    description: Gives access to use /eb timers!
    default: op
  epicboss.location:
    description: Gives access to use /eb location
    default: op
  epicboss.bossegg:
    description: Gives access to use /eb spawnegg
    default: op
  epicboss.reload:
    description: Gives access to use /eb reload
    default: op